<?php
/*=== Приоритеты фильтров ===*/
DEFINE("FILTER_PRIORITY_LOW", 1);
DEFINE("FILTER_PRIORITY_MEDIUM", 50);
DEFINE("FILTER_PRIORITY_HIGH", 150);
DEFINE("FILTER_PRIORITY_SUPERHIGH", 300);
DEFINE("FILTER_PRIORITY_SYSTEM", 10000);

/*=== Константы типа запроса ===*/
DEFINE("REQ_TYPE_GET", 1);
DEFINE("REQ_TYPE_POST", 2);
DEFINE("REQ_TYPE_ALL", 3);

/*=== Константы для хелпера Uri ===*/
DEFINE("URI_RETURN_SITE", 1);
DEFINE("URI_RETURN_PATH", 2);
DEFINE("URI_RETURN_Q", 4);
DEFINE("URI_RETURN_FULL", 7);
?>